/**:
  ros__parameters:
    controllers_name:
    - controller_velocity
    controller_velocity:
      enable_button: 6
      fast_enable_button: 7
      enable_axis: -1
      fast_enable_axis: -1
      axis_sign: 1
      linear:
        x_axis: 4
        y_axis: 3
        scale: 0.2
        fast_scale: 0.6
      angular:
        axis: 0
        scale: 0.2
        fast_scale: 0.6
