/**:
  ros__parameters:
    control_velocity:
      button: 6
      fast_button: 7
      axis: -1
      fast_axis: -1
      axis_sign: 1
      linear:
        x_axis: 4
        y_axis: 3
        scale: 0.15
        fast_scale: 0.3
      angular:
        axis: 0
        scale: 0.5
        fast_scale: 1.0
