/**:
  ros__parameters:
    control_velocity:
      button: 5
      fast_button: 7
      axis: -1
      fast_axis: -1
      axis_sign: 1
      linear:
        x_axis: 1
        y_axis: 0
        scale: 0.2
        fast_scale: 0.5
      angular:
        axis: 3
        scale: 0.3
        fast_scale: 0.6
