/**:
  ros__parameters:
    robot_topic_name:
      joint_states_topic: joint_states
      joint_trajectory_topic:
        head: head_position_controller/joint_trajectory
        arm: arm_position_controller/joint_trajectory
      cmd_vel_topic: wheel_controller/cmd_vel_unstamped
    base_max_speed:
      linear: 1.0
      angular: 1.0
