/**:
  ros__parameters:
    control_joints:
      groups:
      - head
      - arm
      head:
        joints_name:
        - head_camera_tilt_joint
        - head_camera_pan_joint
        head_camera_tilt_joint:
          button: 2
          fast_button: 6
          axis: 1
          axis_sign: 1
          speed: 0.1
          fast_speed: 0.5
        head_camera_pan_joint:
          button: 2
          fast_button: 6
          axis: 0
          axis_sign: 1
          speed: 0.1
          fast_speed: 0.5
      arm:
        joints_name:
        - arm_shoulder_roll_joint
        - arm_shoulder_pitch_joint
        - arm_elbow_pitch_joint
        - arm_forearm_roll_joint
        - arm_wrist_pitch_joint
        - arm_wrist_roll_joint
        arm_shoulder_roll_joint:
          button: 1
          fast_button: 6
          axis: 0
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
        arm_shoulder_pitch_joint:
          button: 1
          fast_button: 6
          axis: 1
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
        arm_elbow_pitch_joint:
          button: 0
          fast_button: 6
          axis: 1
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
        arm_forearm_roll_joint:
          button: 0
          fast_button: 6
          axis: 0
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
        arm_wrist_pitch_joint:
          button: 3
          fast_button: 6
          axis: 1
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
        arm_wrist_roll_joint:
          button: 3
          fast_button: 6
          axis: 0
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
    control_poses:
      trigger: 8
      poses:
        poses_name:
        - initial_pose
        - detecting_pose
        initial_pose:
          button: 2
        detecting_pose:
          button: 0
    control_velocity:
      button: 5
      fast_button: 7
      axis_sign: 1
      linear:
        x_axis: 1
        y_axis: 0
        scale: 0.1
        fast_scale: 0.2
      angular:
        scale: 0.3
        fast_scale: 0.6
