/**:
  ros__parameters:
    control_velocity:
      axis: 6
      fast_axis: 7
      axis_sign: -1
      linear:
        x_axis: 1
        scale: 0.1
        fast_scale: 0.2
      angular:
        axis: 0
        scale: 0.3
        fast_scale: 0.6
