/**:
  ros__parameters:
    control_joints:
      groups_name:
      - head
      - arm
      head:
        joints_name:
        - head_tilt_joint
        - head_pan_joint
        head_tilt_joint:
          button: 2
          fast_button: 6
          axis: 1
          axis_sign: 1
          speed: 0.1
          fast_speed: 0.5
        head_pan_joint:
          button: 2
          fast_button: 6
          axis: 0
          axis_sign: 1
          speed: 0.1
          fast_speed: 0.5
      arm:
        joints_name:
        - arm_shoulder_1_tilt_joint
        - arm_elbow_upper_1_tilt_joint
        - arm_elbow_lower_tilt_joint
        - arm_elbow_lower_pan_joint
        - arm_wrist_tilt_joint
        arm_shoulder_1_tilt_joint:
          button: 1
          fast_button: 6
          axis: 1
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
        arm_elbow_upper_1_tilt_joint:
          button: 1
          fast_button: 6
          axis: 0
          axis_sign: 1
          speed: 0.1
          fast_speed: 0.5
        arm_elbow_lower_tilt_joint:
          button: 0
          fast_button: 6
          axis: 0
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
        arm_elbow_lower_pan_joint:
          button: 0
          fast_button: 6
          axis: 1
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
        arm_wrist_tilt_joint:
          button: 7
          fast_button: 6
          axis: 1
          axis_sign: -1
          speed: 0.1
          fast_speed: 0.5
    control_poses:
      trigger: 8
      poses:
        poses_name:
        - initial_pose
        - detecting_pose
        - trash_pose
        - navigation_pose
        initial_pose:
          button: 2
        detecting_pose:
          button: 1
        trash_pose:
          button: 0
        navigation_pose:
          button: 3
    control_velocity:
      enable_button: 5
      fast_enable_button: 7
      axis_sign: 1
      linear:
        x_axis: 1
        y_axis: 0
        scale: 0.2
        fast_scale: 0.6
      angular:
        axis: 3
        scale: 0.2
        fast_scale: 0.6
