/**:
  ros__parameters:

    control_joints:
      groups:
      - head
      - arm
      head:
        joints_name:
        - head_tilt_joint
        - head_pan_joint
        head_tilt_joint:
          button : 2           # △
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
        head_pan_joint:
          button : 2           # △
          fast_button : 6      # L2
          axis : 0             # 左スティック左右
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
      arm:
        joints_name: 
        - arm_shoulder_1_tilt_joint
        - arm_elbow_upper_1_tilt_joint
        - arm_elbow_lower_tilt_joint
        - arm_elbow_lower_pan_joint
        - arm_wrist_tilt_joint
        arm_shoulder_1_tilt_joint:
          button : 1           # ◯
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
        arm_elbow_upper_1_tilt_joint:
          button : 1           # ◯
          fast_button : 6      # L2
          axis : 0             # 左スティック左右
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
        arm_elbow_lower_tilt_joint:
          button : 0           # ✕
          fast_button : 6      # L2
          axis : 0             # 左スティック左右
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
        arm_elbow_lower_pan_joint:
          button : 0           # ✕
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
        arm_wrist_tilt_joint:
          button : 7           # R2
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5

    control_poses:
      trigger : 8        # shareボタン
      pose_list:
        - initial_pose
        - detecting_pose
        - trash_pose
        - navigation_pose
      initial_pose:
        button : 2            # △ボタン
      detecting_pose:
        button : 1            # ◯ボタン
      trash_pose:
        button : 0            # ✕ボタン
      navigation_pose:
        button : 3            # □ボタン

    control_velocity:
      button : 5            # R1
      fast_button : 7       # R2
      linear_x_axis : 1     # 左スティック上下
      linear_y_axis : 0     # 左スティック左右
      angular_axis : 3      # 右スティック左右
      axis_sign : 1
      linear_scale : 0.1
      angular_scale : 0.3
      fast_linear_scale : 0.2
      fast_angular_scale : 0.6