/**:
  ros__parameters:
    control_velocity:
      enable_axis: 6
      fast_enable_axis: 7
      axis_sign: -1
      linear:
        x_axis: 1
        y_axis: 0
        scale: 0.2
        fast_scale: 0.6
      angular:
        axis: 4
        scale: 0.2
        fast_scale: 0.6
