/**:
  ros__parameters:

    control_velocity:
      control : "button"  # "button" or "axis"
      button : 5            # R1
      fast_button : 7       # R2
      linear_x_axis : 1     # 左スティック上下
      linear_y_axis : 0     # 左スティック左右
      angular_axis : 3      # 右スティック左右
      axis_sign : 1
      linear_scale : 0.1
      angular_scale : 0.3
      fast_linear_scale : 0.2
      fast_angular_scale : 0.6

    control_joints:
      groups:
      - head
      - body
      - arm_left
      - arm_right
      head:
        names:
        - head_tilt_joint
        - head_pan_joint
        head_tilt_joint:
          button : 2           # △
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
        head_pan_joint:
          button : 2           # △
          fast_button : 6      # L2
          axis : 0             # 左スティック左右
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
      body:
        names:
        - body_lift_joint
        body_lift_joint:
          button : 3           # □
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.2
      arm_left:
        names: 
        - arm_left_shoulder_tilt_joint
        - arm_left_upper_roll_joint
        - arm_left_upper_flex_joint
        - arm_left_elbow_joint
        - arm_left_wrist_tilt_joint
        - arm_left_wrist_roll_joint
        arm_left_shoulder_tilt_joint:
          button : 1           # ◯
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
        arm_left_upper_roll_joint:
          button : 1           # ◯
          fast_button : 6      # L2
          axis : 0             # 左スティック左右
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
        arm_left_upper_flex_joint:
          button : 0           # ✕
          fast_button : 6      # L2
          axis : 0             # 左スティック左右
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
        arm_left_elbow_joint:
          button : 0           # ✕
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
        arm_left_wrist_tilt_joint:
          button : 7           # R2
          fast_button : 6      # L2
          axis : 1             # 左スティック上下
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
        arm_left_wrist_roll_joint:
          button : 7           # R2
          fast_button : 6      # L2
          axis : 0             # 左スティック左右
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
      arm_right:
        names: 
        - arm_right_shoulder_tilt_joint
        - arm_right_upper_roll_joint
        - arm_right_upper_flex_joint
        - arm_right_elbow_joint
        - arm_right_wrist_tilt_joint
        - arm_right_wrist_roll_joint
        arm_right_shoulder_tilt_joint:
          button : 1           # ◯
          fast_button : 6      # L2
          axis : 4             # 右スティック上下
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
        arm_right_upper_roll_joint:
          button : 1           # ◯
          fast_button : 6      # L2
          axis : 3             # 右スティック左右
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
        arm_right_upper_flex_joint:
          button : 0           # ✕
          fast_button : 6      # L2
          axis : 3             # 右スティック左右
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5
        arm_right_elbow_joint:
          button : 0           # ✕
          fast_button : 6      # L2
          axis : 4             # 右スティック上下
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
        arm_right_wrist_tilt_joint:
          button : 7           # R2
          fast_button : 6      # L2
          axis : 4             # 右スティック上下
          axis_sign : 1
          speed : 0.1
          fast_speed : 0.5
        arm_right_wrist_roll_joint:
          button : 7           # R2
          fast_button : 6      # L2
          axis : 3             # 右スティック左右
          axis_sign : -1
          speed : 0.1
          fast_speed : 0.5

    control_poses:
      trigger : 8        # shareボタン
      pose_list:
        - initial_pose
        - ninja_pose
        - detecting_high_pose
        - pre_manipulation_pose
      initial_pose:
        button : 2            # △ボタン
      ninja_pose:
        button : 1            # ◯ボタン
      detecting_high_pose:
        button : 0            # ✕ボタン
      pre_manipulation_pose:
        button : 3            # □ボタン