/**:
  ros__parameters:
    control_velocity:
      axis: 3
      linear_x_axis: 1
      linear_y_axis: 0
      angular_axis: 4
      axis_sign: -1
      linear_scale: 0.1
      angular_scale: 0.3
      fast_linear_scale: 0.2
      fast_angular_scale: 0.6
    control_poses:
      pose_action: move_to_pose
      time_from_start: 3.0
      pose_list:
      - initial_pose
      - hand_right_open
      - hand_right_close
      - hand_left_open
      - hand_left_close
      initial_pose:
        button: 0
        groups:
        - head
        - body
        - arm_left
        - arm_right
        - hand_left
        - hand_right
        head:
          joints:
          - head_pan_joint
          - head_tilt_joint
          positions:
          - 0.0
          - 0.0
        body:
          joints:
          - body_lift_joint
          positions:
          - 0.3
        arm_left:
          joints:
          - arm_left_shoulder_tilt_joint
          - arm_left_upper_roll_joint
          - arm_left_upper_flex_joint
          - arm_left_elbow_joint
          - arm_left_lower_flex_joint
          - arm_left_wrist_tilt_joint
          - arm_left_wrist_roll_joint
          positions:
          - -0.75
          - -1.22
          - -0.2
          - 2.5
          - 0.0
          - 0.0
          - 0.0
        arm_right:
          joints:
          - arm_right_shoulder_tilt_joint
          - arm_right_upper_roll_joint
          - arm_right_upper_flex_joint
          - arm_right_elbow_joint
          - arm_right_lower_flex_joint
          - arm_right_wrist_tilt_joint
          - arm_right_wrist_roll_joint
          positions:
          - -0.75
          - -1.22
          - -0.2
          - 2.5
          - 0.0
          - 0.0
          - 0.0
        hand_left:
          joints:
          - hand_left_finger_c_mcp_joint
          - hand_left_finger_c_ip_joint
          - hand_left_finger_l_mcp_joint
          - hand_left_finger_l_pip_joint
          - hand_left_finger_l_dip_joint
          - hand_left_finger_r_pip_joint
          - hand_left_finger_r_dip_joint
          positions:
          - -1.57
          - 0.0
          - -1.5707
          - 1.57
          - 0.0
          - -1.57
          - 0.0
        hand_right:
          joints:
          - hand_right_finger_c_mcp_joint
          - hand_right_finger_c_ip_joint
          - hand_right_finger_l_mcp_joint
          - hand_right_finger_l_pip_joint
          - hand_right_finger_l_dip_joint
          - hand_right_finger_r_pip_joint
          - hand_right_finger_r_dip_joint
          positions:
          - 1.57
          - 0.0
          - 1.57
          - 1.57
          - 0.0
          - -1.57
          - 0.0
      hand_right_open:
        button: -1
        groups:
        - hand_right
        hand_right:
          joints:
          - hand_right_finger_l_pip_joint
          - hand_right_finger_l_dip_joint
          - hand_right_finger_r_pip_joint
          - hand_right_finger_r_dip_joint
          - hand_right_finger_c_mcp_joint
          - hand_right_finger_c_ip_joint
          positions:
          - 1.571
          - 0.0
          - -1.571
          - 0.0
          - 1.571
          - 0.0
      hand_right_close:
        button: -1
        groups:
        - hand_right
        hand_right:
          joints:
          - hand_right_finger_l_pip_joint
          - hand_right_finger_l_dip_joint
          - hand_right_finger_r_pip_joint
          - hand_right_finger_r_dip_joint
          - hand_right_finger_c_mcp_joint
          - hand_right_finger_c_ip_joint
          positions:
          - -0.5
          - -1.571
          - 0.5
          - 1.571
          - -0.5
          - -1.571
      hand_left_open:
        button: -1
        groups:
        - hand_left
        hand_left:
          joints:
          - hand_left_finger_l_pip_joint
          - hand_left_finger_l_dip_joint
          - hand_left_finger_r_pip_joint
          - hand_left_finger_r_dip_joint
          - hand_left_finger_c_mcp_joint
          - hand_left_finger_c_ip_joint
          positions:
          - 1.571
          - 0.0
          - -1.571
          - 0.0
          - -1.571
          - 0.0
      hand_left_close:
        button: -1
        groups:
        - hand_left
        hand_left:
          joints:
          - hand_left_finger_l_pip_joint
          - hand_left_finger_l_dip_joint
          - hand_left_finger_r_pip_joint
          - hand_left_finger_r_dip_joint
          - hand_left_finger_c_mcp_joint
          - hand_left_finger_c_ip_joint
          positions:
          - -0.5
          - -1.571
          - 0.5
          - 1.571
          - 0.5
          - 1.571
      blends_name:
      - hand_right_grip
      - hand_left_grip
      hand_right_grip:
        group: hand_right
        from: hand_right_open
        to: hand_right_close
        enable_axis: 6
        enable_button: -1
        axis: 4
        axis_sign: -1
        to_button: -1
        from_button: -1
        speed: 0.6
      hand_left_grip:
        group: hand_left
        from: hand_left_open
        to: hand_left_close
        enable_axis: 2
        enable_button: -1
        axis: 0
        axis_sign: 1
        to_button: -1
        from_button: -1
        speed: 0.6
    control_joints:
      groups:
      - hand_right
      - hand_left
      hand_right:
        joints_name:
        - hand_right_finger_l_mcp_joint
        hand_right_finger_l_mcp_joint:
          enable_axis: 6
          axis: 5
          axis_sign: -1
          dominant_over: 4
          speed: 0.6
          fast_speed: 0.6
      hand_left:
        joints_name:
        - hand_left_finger_l_mcp_joint
        hand_left_finger_l_mcp_joint:
          enable_axis: 2
          axis: 1
          axis_sign: 1
          dominant_over: 0
          speed: 0.6
          fast_speed: 0.6
    control_target:
      groups:
      - head
      - body
      - arm_right
      - hand_right
      - arm_left
      - hand_left
      head:
        enable_axis: 2
        target_frame_name: hmd_odom
        motion_scale: 1.0
        joints_name:
        - head_pan_joint
        - head_tilt_joint
        head_pan_joint:
          type: rotation
          axis: yaw
          sign: 1
        head_tilt_joint:
          type: rotation
          axis: pitch
          sign: -1
      body:
        enable_axis: 2
        target_frame_name: hmd_odom
        motion_scale: 1.0
        joints_name:
        - body_lift_joint
        body_lift_joint:
          type: prismatic
          axis: z
          sign: 1
      arm_right:
        controller_frame_name: right_controller_odom
        controller_echo_frame_name: right_controller_link
        enable_axis: 7
        motion_scale: 2.0
        end_effector_frame_name: hand_right_end_effector_link
        target_frame_name: right_target_link
        proximity_threshold: 0.0
        proximity_angle_threshold: 0.0
      hand_right:
        pose_button: 6
        pose_open: two_fingers_open_pose
        pose_close: two_fingers_grasp_pose
        pose_action: move_right_hand_to_pose
      arm_left:
        controller_frame_name: left_controller_odom
        controller_echo_frame_name: left_controller_link
        enable_axis: 7
        motion_scale: 2.0
        end_effector_frame_name: hand_left_end_effector_link
        target_frame_name: left_target_link
        proximity_threshold: 0.0
        proximity_angle_threshold: 0.0
      hand_left:
        pose_button: 2
        pose_open: two_fingers_open_pose
        pose_close: two_fingers_grasp_pose
        pose_action: move_left_hand_to_pose
