/**:
  ros__parameters:
    robot_topic_name:
      joint_states_topic: joint_states
      joint_trajectory_topic:
        head: head_position_controller/joint_trajectory
        body: body_position_controller/joint_trajectory
        arm_left: arm_left_position_controller/joint_trajectory
        arm_right: arm_right_position_controller/joint_trajectory
        hand_left: hand_left_position_controller/joint_trajectory
        hand_right: hand_right_position_controller/joint_trajectory
      cmd_vel_topic: cmd_vel